services:
  schoolprojectstudentmoduleapi:
    build:
      context: .
      dockerfile: src/SchoolProject.StudentModule.Api/Dockerfile
    ports:
      - 5207:5207
    networks:
      - gateway_network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=school
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  schoolprojectusermoduleapi:
    build:
      context: .
      dockerfile: src/SchoolProject.UserModule.Api/Dockerfile
    ports:
      - 5124:5124
    networks:
      - gateway_network
    volumes:
      - ./logs:/app/logs
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=schoolprojectusermodule
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  schoolprojectapigateway:
    build:
      context: .
      dockerfile: src/SchoolProject.ApiGateway/Dockerfile
    ports:
      - 5181:5181
    networks:
      - gateway_network
    depends_on:
      - schoolprojectstudentmoduleapi
      - schoolprojectusermoduleapi

  mysql: 
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gateway_network

networks:
  gateway_network:
    driver: bridge

volumes:
  mysql_data:
  datafiles: