# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  schoolprojectapigateway:
    image: schoolprojectapigateway
    build:
      context: .
      dockerfile: src/SchoolProject.ApiGateway/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5181:5181
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
